const CharList = {
    'ssr': [
        { path: "images/Venti.png", name: "温迪", type: "角色", rarity: "5★" },
        { path: "images/char_zhongli.png", name: "钟离", type: "角色", rarity: "5★" },
        { path: "images/char_raiden.png", name: "雷电将军", type: "角色", rarity: "5★" },
        { path: "images/char_nahida.png", name: "纳西妲", type: "角色", rarity: "5★" },
        { path: "images/Klee.png", name: "可莉", type: "角色", rarity: "5★" },
        { path: "images/Jean.png", name: "琴", type: "角色", rarity: "5★" },
        { path: "images/Diluc.png", name: "迪卢克", type: "角色", rarity: "5★" },
        { path: "images/Eula.png", name: "优菈", type: "角色", rarity: "5★" },
        { path: "images/Mona.png", name: "莫娜", type: "角色", rarity: "5★" },
        { path: "images/Tartaglia.png", name: "达达利亚", type: "角色", rarity: "5★" },
        { path: "images/Xiao.png", name: "魈", type: "角色", rarity: "5★" },
        { path: "images/Shenhe.png", name: "申鹤", type: "角色", rarity: "5★" },
        { path: "images/Hu_Tao.png", name: "胡桃", type: "角色", rarity: "5★" },
        { path: "images/Keqing.png", name: "刻晴", type: "角色", rarity: "5★" },
        { path: "images/Ganyu.png", name: "甘雨", type: "角色", rarity: "5★" },
        { path: "images/Tighnari.png", name: "提纳里", type: "角色", rarity: "5★" },
        { path: "images/Cyno.png", name: "赛诺", type: "角色", rarity: "5★" },
        { path: "images/Yae_Miko.png", name: "八重神子", type: "角色", rarity: "5★" },
        { path: "images/Kamizato_Ayaka.png", name: "神里绫华", type: "角色", rarity: "5★" },
        { path: "images/Kamizato_Ayato.png", name: "神里绫人", type: "角色", rarity: "5★" },
        { path: "images/Yoimiya.png", name: "宵宫", type: "角色", rarity: "5★" },
        { path: "images/Sangonomiya_Kokomi.png", name: "珊瑚宫心海", type: "角色", rarity: "5★" },
        { path: "images/Maguu_Kenki.png", name: "魔偶剑鬼", type: "魔物", rarity: "5★" },
        { path: "images/Rhodeia_of_Loch.png", name: "纯水精灵·洛蒂娅", type: "魔物", rarity: "5★" },
        { path: "images/Gold_Lawachurls.png", name: "黄金王兽", type: "魔物", rarity: "5★" },
        { path: "images/Jadeplume_Terrorshroom.png", name: "翠翎恐蕈", type: "魔物", rarity: "5★" },
        { path: "images/Agents.png", name: "愚人众·债务处理人", type: "魔物", rarity: "5★" },
        { path: "images/Mirror_Maiden.png", name: "愚人众·藏镜仕女", type: "魔物", rarity: "5★" },
        { path: "images/Hydro_Tulpa.png",name: "水形幻人",type: "魔物",rarity: "5★"},
        { path: "images/Gluttonous_Yumkasaur_Mountain_King.png",name: "贪食匿叶龙山王",type: "魔物",rarity: "5★"},
        { path: "images/Black_Serpent_Knight_Rockbreaker Ax.png",name: "黑蛇骑士．摧岩之钺",type: "魔物",rarity: "5★"},
        { path: "images/Amos_bow.png", name: "阿莫斯之弓", type: "武器", rarity: "5★" },
        { path: "images/A_Thousand_Floating_Dreams.png", name: "千夜浮梦", type: "武器", rarity: "5★" },
        { path: "images/Engulfing_Lightning.png", name: "薙草之稻光", type: "武器", rarity: "5★" },
        { path: "images/Skyward_Atlas.png", name: "天空之卷", type: "武器", rarity: "5★" },
        { path: "images/Skyward_Harp.png", name: "天空之翼", type: "武器", rarity: "5★" },
        { path: "images/Skyward_Spine.png", name: "天空之脊", type: "武器", rarity: "5★" },
        { path: "images/Wolf_Gravestone.png", name: "狼的末路", type: "武器", rarity: "5★" }
    ],
    'sr': [
        { path: "images/Kaeya.png", name: "凯亚", type: "角色", rarity: "4★" },
        { path: "images/Amber.png", name: "安柏", type: "角色", rarity: "4★" },
        { path: "images/Barbara.png", name: "芭芭拉", type: "角色", rarity: "4★" },
        { path: "images/Noelle.png", name: "诺艾尔", type: "角色", rarity: "4★" },
        { path: "images/Diona.png", name: "迪奥娜", type: "角色", rarity: "4★" },
        { path: "images/Fischl.png", name: "菲谢尔", type: "角色", rarity: "4★" },
        { path: "images/Sucrose.png", name: "砂糖", type: "角色", rarity: "4★" },
        { path: "images/Razor.png", name: "雷泽", type: "角色", rarity: "4★" },
        { path: "images/char_bennett.png", name: "班尼特", type: "角色", rarity: "4★" },
        { path: "images/Ningguang.png", name: "凝光", type: "角色", rarity: "4★" },
        { path: "images/Beidou.png", name: "北斗", type: "角色", rarity: "4★" },
        { path: "images/char_xingqiu.png", name: "行秋", type: "角色", rarity: "4★" },
        { path: "images/Chongyun.png", name: "重云", type: "角色", rarity: "4★" },
        { path: "images/char_xiangling.png", name: "香菱", type: "角色", rarity: "4★" },
        { path: "images/Collei.png", name: "柯莱", type: "角色", rarity: "4★" },
        { path: "images/Kujo_Sara.png", name: "九条裟罗", type: "角色", rarity: "4★" },
        { path: "images/Anemo_Samachurl.png",name: "丘丘风萨满",type: "魔物",rarity: "4★"},
        { path: "images/Electro_Samachurl.png",name: "丘丘雷萨满",type: "魔物",rarity: "4★"},
        { path: "images/Hydro_Samachurl.png",name: "丘丘水萨满",type: "魔物",rarity: "4★"},
        { path: "images/Dendro_Samachurl.png",name: "丘丘草萨满",type: "魔物",rarity: "4★"},
        { path: "images/Geo_Samachurl.png",name: "丘丘岩萨满",type: "魔物",rarity: "4★"},
        { path: "images/Pyro_Abyss_Mage.png",name: "火深渊法师",type: "魔物",rarity: "4★"},
        { path: "images/Electro_Abyss_Mage.png",name: "雷深渊法师",type: "魔物",rarity: "4★"},
        { path: "images/Hydro_Abyss_Mage.png",name: "水深渊法师",type: "魔物",rarity: "4★"},
        { path: "images/Cryo_Abyss_Mage.png",name: "冰深渊法师",type: "魔物",rarity: "4★"},
        { path: "images/Blazing_Axe_Mitachurl.png",name: "火斧丘丘暴徒",type: "魔物",rarity: "4★"},
        { path: "images/Crackling_Axe_Mitachurl.png",name: "雷斧丘丘暴徒",type: "魔物",rarity: "4★"},
        { path: "images/Wooden_Shieldwall_Mitachurl.png",name: "木盾丘丘暴徒",type: "魔物",rarity: "4★"},
        { path: "images/Rock_Shieldwall_Mitachurl.png",name: "岩盾丘丘暴徒",type: "魔物",rarity: "4★"},
        { path: "images/Ice_Shieldwall_Mitachurl.png",name: "冰盾丘丘暴徒",type: "魔物",rarity: "4★"},
        { path: "images/Kairagi_Dancing Thunder.png",name: "海乱鬼·雷腾",type: "魔物",rarity: "4★"},
        { path: "images/Kairagi_Fiery_Might.png",name: "海乱鬼·炎威",type: "魔物",rarity: "4★"},
        { path: "images/Grounded_Hydroshroom.png",name: "陆行水本真蕈",type: "魔物",rarity: "4★"},
        { path: "images/Grounded_Geoshroom.png",name: "陆行岩本真蕈",type: "魔物",rarity: "4★"},
        { path: "images/Winged_Dendroshroom.png",name: "有翼草本真蕈",type: "魔物",rarity: "4★"},
        { path: "images/Winged_Cryoshroom.png",name: "有翼冰本真蕈",type: "魔物",rarity: "4★"},
        { path: "images/Thundercraven_Rifthound_Whelp.png",name: "嗜雷·兽境猎犬",type: "魔物",rarity: "4★"},
        { path: "images/Rockfond_Rifthound_Whelp.png",name: "嗜岩·兽境猎犬",type: "魔物",rarity: "4★"},
        { path: "images/Suppression_Specialist_Mek.png",name: "攻坚特化型机关",type: "魔物",rarity: "4★"},
        { path: "images/Annihilation_Specialist_Mek.png",name: "歼灭特化型机关",type: "魔物",rarity: "4★"},
        { path: "images/Fatui_Skirmisher-Anemoboxer_Vanguard.png",name: "愚人众先遣队·风拳前锋军",type: "魔物",rarity: "4★"},
        { path: "images/Fatui_Skirmisher-Cryogunner_Legionnaire.png",name: "愚人众先遣队·冰铳重卫士",type: "魔物",rarity: "4★"},
        { path: "images/Fatui_Skirmisher-Hydrogunner_Legionnaire.png",name: "愚人众先遣队·水铳重卫士",type: "魔物",rarity: "4★"},
        { path: "images/Consecrated_Horned_Crocodile.png",name: "圣骸角鳄",type: "魔物",rarity: "4★"},
        { path: "images/Sacrificial_Sword.png", name: "祭礼剑", type: "武器", rarity: "4★" },
        { path: "images/Sacrificial_Fragments.png", name: "祭礼残章", type: "武器", rarity: "4★" },
        { path: "images/Sacrificial_Greatsword.png", name: "祭礼大剑", type: "武器", rarity: "4★" },
        { path: "images/Sacrificial_Bow.png", name: "祭礼弓", type: "武器", rarity: "4★" },
        { path: "images/Lithic_Spear.png", name: "千岩长枪", type: "武器", rarity: "4★" },
        { path: "images/Large_Cryo_Slime.png", name: "大型冰史莱姆", type: "魔物", rarity: "4★" },
        { path: "images/Large_Hydro_Slime.png", name: "大型水史莱姆", type: "魔物", rarity: "4★" }
    ],
    'r': [
        { path: "images/Hydro_Slime.png", name: "水史莱姆", type: "魔物", rarity: "3★" },
        { path: "images/Cryo_Slime.png", name: "冰史莱姆", type: "魔物", rarity: "3★" },
        { path: "images/Electro_Slime.png", name: "雷史莱姆", type: "魔物", rarity: "3★" },
        { path: "images/Arithmetic_Enhancer_Mek.png",name: "机关·算力振幅器",type: "魔物",rarity: "3★"},
        { path: "images/Pyro_Whopperflower.png",name: "炽热骗骗花",type: "魔物",rarity: "3★"},
        { path: "images/Hilichurl_Fighter.png",name: "打手丘丘人",type: "魔物",rarity: "3★"},
        { path: "images/Hilichurl_Berserker.png",name: "冲锋丘丘人",type: "魔物",rarity: "3★"},
        { path: "images/Hilichurl_Shooter.png",name: "射手丘丘人",type: "魔物",rarity: "3★"},
        { path: "images/Electro_Hilichurl_Shooter.png",name: "雷弹丘丘人",type: "魔物",rarity: "3★"},
        { path: "images/Cryo_Hilichurl_Shooter.png",name: "冰箭丘丘人",type: "魔物",rarity: "3★"},
        { path: "images/Nobushi_Jintouban.png",name: "野伏·阵刀番",type: "魔物",rarity: "3★"},
        { path: "images/Nobushi_Hitsukeban.png",name: "野伏·火付番",type: "魔物",rarity: "3★"},
        { path: "images/Nobushi_Kikouban.png",name: "野伏·机巧番",type: "魔物",rarity: "3★"},
        { path: "images/weapon_bow.png", name: "猎弓", type: "武器", rarity: "3★" },
        { path: "images/weapon_claymore.png", name: "训练大剑", type: "武器", rarity: "3★" },
        { path: "images/weapon_book.png", name: "讨龙英杰谭", type: "武器", rarity: "3★" },
        { path: "images/Traverler_Sword.png", name: "旅行剑", type: "武器", rarity: "3★" },
        { path: "images/White_Tassel.png", name: "白缨枪", type: "武器", rarity: "3★" }
    ]
};


